name: test

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * *" # JST 09:00

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
          - head

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Cache vendor/bundle
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: v1-gem-${{ runner.os }}-${{ matrix.ruby }}-${{ github.sha }}
          restore-keys: |
            v1-gem-${{ runner.os }}-${{ matrix.ruby }}-
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
      - name: bundle update
        run: |
          set -xe
          bundle config path vendor/bundle
          bundle update --jobs $(nproc) --retry 3
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
      - name: Run ${{ matrix.test_framework }}
        run: |
          set -xe
          bundle exec rspec
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
